[package]
name = "rustfest"
version = "0.1.0"
authors = ["Jef <jackefransham@gmail.com>"]

[dependencies]
combine = "3.6"
hashbrown = "0.1"

[profile.bench]
debug = true

[profile.release]
debug = true
